03_onlineshop/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path("", detail, name="detail"),
    path("add/<int:product_id>/", add, name="product_add"),
    path("remove/<product_id>/", remove, name="product_remove"),
]

03_onlineshop/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]

03_onlineshop/shop/urls.py
from django.urls import path
from .views import *

app_name = "shop"

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
]

03_onlineshop/cart/models.py
from django.db import models

# Create your models here.

03_onlineshop/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    meta_description = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_in_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    meta_description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created', '-updated']
        index_together = [['id','slug']]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

03_onlineshop/cart/forms.py
from django import forms

# 사용자 클라이언트 화면에 입력폼을 만들어줄 때,
# 클라이언트에 입력한 데이터에 대한 전처리

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    # boolfield는 required flase로
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

03_onlineshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST


from shop.models import Product
from .forms import AddProductForm
from .cart import Cart

@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    # 클라이언트 -> 서버로 데이터 전달 (클라이언트에서 받은 데이터는 form을 활용해 clean data로 사용 권장)
    # 유효성 검사, injection 전처리
    form = AddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], is_update=cd["is_update"])

        return redirect("cart:detail")

# 제품을 카트에서 제거
def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:detail")

def detail(request):
    cart = Cart(request)
    for product in cart:
        product["quantity_form"] = AddProductForm(initial={"quantity": product["quantity"], "is_update": True})
    return render(request, "cart/detail.html", {"cart": cart})

03_onlineshop/shop/views.py
import requests

from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import *
from cart.forms import AddProductForm

def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True)
    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)
    return render(request,
                  'shop/list.html',
                  {
                      'current_category':current_category,
                      'categories':categories,
                      'products':products
                  })

def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity':1})
    return render(request, 'shop/detail.html', {'product':product, 'add_to_cart':add_to_cart})

03_onlineshop/shop/templates/shop/detail.html
{% extends 'base.html' %}

{% block title %}Product Detail
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <img src="{{product.image.url}}" width="100%">
        </div>
        <div class="col">
            <h1 class="display-6">{{product.name}}</h1>
            <p><span class="badge badge-secondary">Price</span>{{product.price}}</p>

            <form action="{% url 'cart:product_add' product.id %}" method="post">
                {{add_to_cart}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary btn-sm" value="Add to Cart">
            </form>

            <h5><span class="badge badge-secondary">Description</span>{{product.description|linebreaks}}</h5>
        </div>
    </div>
{% endblock %}

03_onlineshop/shop/templates/shop/list.html
{% extends 'base.html' %}

{% block title %}Category Page
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-2">
        <div class="list-group">
            <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">All</a>
            {% for c in categories %}
             <a href="{{c.get_absolute_url}}" class="list-group-item {% if current_category.slug == c.slug %}active{% endif %}">{{c.name}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col">
        <div class="alert alert-info">
            {% if current_category %}{{current_category.name}}{% else %}All Products{% endif %}
        </div>
        <div class="row">
            {% for product in products %}
            <div class="col-4">
                <div class="card">
                    {%if product.image%}<img class="cart-img-top" src="{{product.image.url}}" alt="Product Image" style="width:100%;">{%endif%}
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">{{product.description}} <span class="badge badge-secondary">{{product.price}}</span></p>
                        <a href="{{product.get_absolute_url}}" class="btn btn-primary">View Detail</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

03_onlineshop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
            integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
            integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK"
            crossorigin="anonymous"></script>

    {% block script %}
    {% endblock %}

    {% block style %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Django onlineshop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:product_all' %}">Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:detail' %}">
                        Cart
                        {% if cart|length > 0 %}
                        ${{cart.get_product_total}} with {{cart|length}} items
                        {% else %}
                        : Empty
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Dropdown link
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>